

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class VertragItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität VertragItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VertragItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public VertragItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.VertragItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.VertragItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.VertragItem.DetailsClass.SetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime von
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.von);
            }
            set
            {
                global::LightSwitchApplication.VertragItem.DetailsClass.SetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.von, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void von_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void von_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void von_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime bis
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.bis);
            }
            set
            {
                global::LightSwitchApplication.VertragItem.DetailsClass.SetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.bis, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void bis_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void bis_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void bis_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.VertragItem.DetailsClass.SetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Dauer
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Dauer);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Dauer_Compute(ref int result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Dauer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.MitarbeiterItem MitarbeiterItem
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.MitarbeiterItem);
            }
            set
            {
                global::LightSwitchApplication.VertragItem.DetailsClass.SetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.MitarbeiterItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItem_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.BeschäftigungsArtItem BeschäftigungsArtItem
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.BeschäftigungsArtItem);
            }
            set
            {
                global::LightSwitchApplication.VertragItem.DetailsClass.SetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.BeschäftigungsArtItem, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItem_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItem_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItem_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.StellenanteilItem> StellenanteilItemCollection
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetValue(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.StellenanteilItemCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.StellenanteilItem> StellenanteilItemCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.VertragItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.StellenanteilItemCollection);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.VertragItem,
                global::LightSwitchApplication.VertragItem.DetailsClass,
                global::LightSwitchApplication.VertragItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.VertragItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass>.Entry
                __VertragItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.VertragItem.DetailsClass.__VertragItem_CreateNew,
                    global::LightSwitchApplication.VertragItem.DetailsClass.__VertragItem_Created,
                    global::LightSwitchApplication.VertragItem.DetailsClass.__VertragItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.VertragItem __VertragItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.VertragItem> es)
            {
                return new global::LightSwitchApplication.VertragItem(es);
            }
            private static void __VertragItem_Created(global::LightSwitchApplication.VertragItem e)
            {
                e.VertragItem_Created();
            }
            private static bool __VertragItem_AllowSaveWithErrors(global::LightSwitchApplication.VertragItem e)
            {
                bool result = false;
                e.VertragItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.VertragItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime> von
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.von) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime> bis
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.bis) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int> Dauer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.Dauer) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem> MitarbeiterItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.MitarbeiterItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.BeschäftigungsArtItem> BeschäftigungsArtItem
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.BeschäftigungsArtItem) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.BeschäftigungsArtItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.StellenanteilItem> StellenanteilItemCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.StellenanteilItemCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.StellenanteilItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new global::System.DateTime von { get; set; }
                new global::System.DateTime bis { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation MitarbeiterItem { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation BeschäftigungsArtItem { get; set; }
                new global::System.Collections.IEnumerable StellenanteilItemCollection { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>.Entry
                    von = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>.Entry(
                        "von",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._von_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._von_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._von_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._von_GetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._von_SetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._von_OnValueChanged);
                private static void _von_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._von, sf);
                }
                private static bool _von_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.von_IsReadOnly(ref result);
                    return result;
                }
                private static void _von_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.von_Validate(r);
                }
                private static global::System.DateTime _von_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.von;
                }
                private static void _von_SetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.von = global::LightSwitchApplication.VertragItem.DetailsClass.TruncateDate(v);
                }
                private static void _von_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.von_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>.Entry
                    bis = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>.Entry(
                        "bis",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._bis_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._bis_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._bis_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._bis_GetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._bis_SetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._bis_OnValueChanged);
                private static void _bis_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._bis, sf);
                }
                private static bool _bis_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.bis_IsReadOnly(ref result);
                    return result;
                }
                private static void _bis_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.bis_Validate(r);
                }
                private static global::System.DateTime _bis_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.bis;
                }
                private static void _bis_SetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.bis = global::LightSwitchApplication.VertragItem.DetailsClass.TruncateDate(v);
                }
                private static void _bis_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.bis_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>.Entry
                    Dauer = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>.Entry(
                        "Dauer",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Dauer_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Dauer_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._Dauer_ComputeValue);
                private static void _Dauer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Dauer, sf);
                }
                private static void _Dauer_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Dauer_Validate(r);
                }
                private static int _Dauer_ComputeValue(global::LightSwitchApplication.VertragItem e)
                {
                    int value = default(int);
                    e.Dauer_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Entry
                    MitarbeiterItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Entry(
                        "MitarbeiterItem",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._MitarbeiterItem_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._MitarbeiterItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._MitarbeiterItem_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._MitarbeiterItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._MitarbeiterItem_GetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._MitarbeiterItem_SetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._MitarbeiterItem_Refresh,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._MitarbeiterItem_OnValueChanged);
                private static void _MitarbeiterItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MitarbeiterItem, sf);
                }
                private static bool _MitarbeiterItem_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.MitarbeiterItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _MitarbeiterItem_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MitarbeiterItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _MitarbeiterItem_GetCoreImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MitarbeiterItem;
                }
                private static global::LightSwitchApplication.MitarbeiterItem _MitarbeiterItem_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.MitarbeiterItem, global::LightSwitchApplication.MitarbeiterItem.DetailsClass>(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.MitarbeiterItem, ref d._MitarbeiterItem);
                }
                private static void _MitarbeiterItem_SetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d, global::LightSwitchApplication.MitarbeiterItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.MitarbeiterItem, ref d._MitarbeiterItem, (i, ev) => i.MitarbeiterItem = ev, v);
                }
                private static void _MitarbeiterItem_Refresh(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.MitarbeiterItem, ref d._MitarbeiterItem);
                }
                private static void _MitarbeiterItem_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.MitarbeiterItem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.BeschäftigungsArtItem>.Entry
                    BeschäftigungsArtItem = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.BeschäftigungsArtItem>.Entry(
                        "BeschäftigungsArtItem",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._BeschäftigungsArtItem_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._BeschäftigungsArtItem_ComputeIsReadOnly,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._BeschäftigungsArtItem_Validate,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._BeschäftigungsArtItem_GetCoreImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._BeschäftigungsArtItem_GetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._BeschäftigungsArtItem_SetImplementationValue,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._BeschäftigungsArtItem_Refresh,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._BeschäftigungsArtItem_OnValueChanged);
                private static void _BeschäftigungsArtItem_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.BeschäftigungsArtItem>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._BeschäftigungsArtItem, sf);
                }
                private static bool _BeschäftigungsArtItem_ComputeIsReadOnly(global::LightSwitchApplication.VertragItem e)
                {
                    bool result = false;
                    e.BeschäftigungsArtItem_IsReadOnly(ref result);
                    return result;
                }
                private static void _BeschäftigungsArtItem_Validate(global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.BeschäftigungsArtItem_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _BeschäftigungsArtItem_GetCoreImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.BeschäftigungsArtItem;
                }
                private static global::LightSwitchApplication.BeschäftigungsArtItem _BeschäftigungsArtItem_GetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.BeschäftigungsArtItem, global::LightSwitchApplication.BeschäftigungsArtItem.DetailsClass>(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.BeschäftigungsArtItem, ref d._BeschäftigungsArtItem);
                }
                private static void _BeschäftigungsArtItem_SetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass d, global::LightSwitchApplication.BeschäftigungsArtItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.BeschäftigungsArtItem, ref d._BeschäftigungsArtItem, (i, ev) => i.BeschäftigungsArtItem = ev, v);
                }
                private static void _BeschäftigungsArtItem_Refresh(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.BeschäftigungsArtItem, ref d._BeschäftigungsArtItem);
                }
                private static void _BeschäftigungsArtItem_OnValueChanged(global::LightSwitchApplication.VertragItem e)
                {
                    e.BeschäftigungsArtItem_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.StellenanteilItem>.Entry
                    StellenanteilItemCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.StellenanteilItem>.Entry(
                        "StellenanteilItemCollection",
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._StellenanteilItemCollection_Stub,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._StellenanteilItemCollection_GetReferencedEntities,
                        global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties._StellenanteilItemCollection_GetEntityCollection);
                private static void _StellenanteilItemCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.VertragItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.StellenanteilItem>.Data> c, global::LightSwitchApplication.VertragItem.DetailsClass d, object sf)
                {
                    c(d, ref d._StellenanteilItemCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.StellenanteilItem> _StellenanteilItemCollection_GetReferencedEntities(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.StellenanteilItem, global::LightSwitchApplication.StellenanteilItem.DetailsClass>(global::LightSwitchApplication.VertragItem.DetailsClass.PropertySetProperties.StellenanteilItemCollection, ref d._StellenanteilItemCollection);
                }
                private static global::System.Collections.IEnumerable _StellenanteilItemCollection_GetEntityCollection(global::LightSwitchApplication.VertragItem.DetailsClass d)
                {
                    return d.ImplementationEntity.StellenanteilItemCollection;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>.Data _von;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.DateTime>.Data _bis;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, int>.Data _Dauer;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Data _MitarbeiterItem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.BeschäftigungsArtItem>.Data _BeschäftigungsArtItem;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.VertragItem, global::LightSwitchApplication.VertragItem.DetailsClass, global::LightSwitchApplication.StellenanteilItem>.Data _StellenanteilItemCollection;
            
        }
    
        #endregion
    }
    
    #endregion
}
