

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class AbteilungItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität AbteilungItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public AbteilungItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public AbteilungItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.AbteilungItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.AbteilungItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.AbteilungItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Kürzel
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Kürzel);
            }
            set
            {
                global::LightSwitchApplication.AbteilungItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Kürzel, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Kürzel_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Kürzel_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Kürzel_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Langname
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Langname);
            }
            set
            {
                global::LightSwitchApplication.AbteilungItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Langname, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Langname_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Langname_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Langname_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.AbteilungItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.MitarbeiterItem> MitarbeiterItemCollection
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.MitarbeiterItemCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.MitarbeiterItem> MitarbeiterItemCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.MitarbeiterItemCollection);
            }
        }

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.ProjektItem> ProjektItemCollection
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.ProjektItemCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.ProjektItem> ProjektItemCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.ProjektItemCollection);
            }
        }

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.MitarbeiterItem Abteilungsleiter
        {
            get
            {
                return global::LightSwitchApplication.AbteilungItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Abteilungsleiter);
            }
            set
            {
                global::LightSwitchApplication.AbteilungItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Abteilungsleiter, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Abteilungsleiter_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Abteilungsleiter_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Abteilungsleiter_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.AbteilungItem,
                global::LightSwitchApplication.AbteilungItem.DetailsClass,
                global::LightSwitchApplication.AbteilungItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass>.Entry
                __AbteilungItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.AbteilungItem.DetailsClass.__AbteilungItem_CreateNew,
                    global::LightSwitchApplication.AbteilungItem.DetailsClass.__AbteilungItem_Created,
                    global::LightSwitchApplication.AbteilungItem.DetailsClass.__AbteilungItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.AbteilungItem __AbteilungItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.AbteilungItem> es)
            {
                return new global::LightSwitchApplication.AbteilungItem(es);
            }
            private static void __AbteilungItem_Created(global::LightSwitchApplication.AbteilungItem e)
            {
                e.AbteilungItem_Created();
            }
            private static bool __AbteilungItem_AllowSaveWithErrors(global::LightSwitchApplication.AbteilungItem e)
            {
                bool result = false;
                e.AbteilungItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string> Kürzel
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Kürzel) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string> Langname
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Langname) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem> MitarbeiterItemCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.MitarbeiterItemCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.ProjektItem> ProjektItemCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.ProjektItemCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.ProjektItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem> Abteilungsleiter
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Abteilungsleiter) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Kürzel { get; set; }
                new string Langname { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable MitarbeiterItemCollection { get; }
                new global::System.Collections.IEnumerable ProjektItemCollection { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Abteilungsleiter { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.AbteilungItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.AbteilungItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Entry
                    Kürzel = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Entry(
                        "Kürzel",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Kürzel_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Kürzel_ComputeIsReadOnly,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Kürzel_Validate,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Kürzel_GetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Kürzel_SetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Kürzel_OnValueChanged);
                private static void _Kürzel_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Kürzel, sf);
                }
                private static bool _Kürzel_ComputeIsReadOnly(global::LightSwitchApplication.AbteilungItem e)
                {
                    bool result = false;
                    e.Kürzel_IsReadOnly(ref result);
                    return result;
                }
                private static void _Kürzel_Validate(global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Kürzel_Validate(r);
                }
                private static string _Kürzel_GetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Kürzel;
                }
                private static void _Kürzel_SetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Kürzel = v;
                }
                private static void _Kürzel_OnValueChanged(global::LightSwitchApplication.AbteilungItem e)
                {
                    e.Kürzel_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Entry
                    Langname = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Entry(
                        "Langname",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Langname_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Langname_ComputeIsReadOnly,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Langname_Validate,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Langname_GetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Langname_SetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Langname_OnValueChanged);
                private static void _Langname_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Langname, sf);
                }
                private static bool _Langname_ComputeIsReadOnly(global::LightSwitchApplication.AbteilungItem e)
                {
                    bool result = false;
                    e.Langname_IsReadOnly(ref result);
                    return result;
                }
                private static void _Langname_Validate(global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Langname_Validate(r);
                }
                private static string _Langname_GetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Langname;
                }
                private static void _Langname_SetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Langname = v;
                }
                private static void _Langname_OnValueChanged(global::LightSwitchApplication.AbteilungItem e)
                {
                    e.Langname_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.AbteilungItem e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.AbteilungItem e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.AbteilungItem e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.AbteilungItem e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.AbteilungItem e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.AbteilungItem e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.AbteilungItem e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.AbteilungItem e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.AbteilungItem e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.AbteilungItem e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Entry
                    MitarbeiterItemCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Entry(
                        "MitarbeiterItemCollection",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._MitarbeiterItemCollection_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._MitarbeiterItemCollection_GetReferencedEntities,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._MitarbeiterItemCollection_GetEntityCollection);
                private static void _MitarbeiterItemCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._MitarbeiterItemCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MitarbeiterItem> _MitarbeiterItemCollection_GetReferencedEntities(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.MitarbeiterItem, global::LightSwitchApplication.MitarbeiterItem.DetailsClass>(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.MitarbeiterItemCollection, ref d._MitarbeiterItemCollection);
                }
                private static global::System.Collections.IEnumerable _MitarbeiterItemCollection_GetEntityCollection(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.MitarbeiterItemCollection;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.ProjektItem>.Entry
                    ProjektItemCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.ProjektItem>.Entry(
                        "ProjektItemCollection",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._ProjektItemCollection_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._ProjektItemCollection_GetReferencedEntities,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._ProjektItemCollection_GetEntityCollection);
                private static void _ProjektItemCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.ProjektItem>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._ProjektItemCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.ProjektItem> _ProjektItemCollection_GetReferencedEntities(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.ProjektItem, global::LightSwitchApplication.ProjektItem.DetailsClass>(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.ProjektItemCollection, ref d._ProjektItemCollection);
                }
                private static global::System.Collections.IEnumerable _ProjektItemCollection_GetEntityCollection(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.ProjektItemCollection;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Entry
                    Abteilungsleiter = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Entry(
                        "Abteilungsleiter",
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Abteilungsleiter_Stub,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Abteilungsleiter_ComputeIsReadOnly,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Abteilungsleiter_Validate,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Abteilungsleiter_GetCoreImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Abteilungsleiter_GetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Abteilungsleiter_SetImplementationValue,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Abteilungsleiter_Refresh,
                        global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties._Abteilungsleiter_OnValueChanged);
                private static void _Abteilungsleiter_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AbteilungItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Data> c, global::LightSwitchApplication.AbteilungItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Abteilungsleiter, sf);
                }
                private static bool _Abteilungsleiter_ComputeIsReadOnly(global::LightSwitchApplication.AbteilungItem e)
                {
                    bool result = false;
                    e.Abteilungsleiter_IsReadOnly(ref result);
                    return result;
                }
                private static void _Abteilungsleiter_Validate(global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Abteilungsleiter_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Abteilungsleiter_GetCoreImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Abteilungsleiter;
                }
                private static global::LightSwitchApplication.MitarbeiterItem _Abteilungsleiter_GetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.MitarbeiterItem, global::LightSwitchApplication.MitarbeiterItem.DetailsClass>(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Abteilungsleiter, ref d._Abteilungsleiter);
                }
                private static void _Abteilungsleiter_SetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass d, global::LightSwitchApplication.MitarbeiterItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Abteilungsleiter, ref d._Abteilungsleiter, (i, ev) => i.Abteilungsleiter = ev, v);
                }
                private static void _Abteilungsleiter_Refresh(global::LightSwitchApplication.AbteilungItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.AbteilungItem.DetailsClass.PropertySetProperties.Abteilungsleiter, ref d._Abteilungsleiter);
                }
                private static void _Abteilungsleiter_OnValueChanged(global::LightSwitchApplication.AbteilungItem e)
                {
                    e.Abteilungsleiter_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Data _Kürzel;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Data _Langname;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Data _MitarbeiterItemCollection;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.ProjektItem>.Data _ProjektItemCollection;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AbteilungItem, global::LightSwitchApplication.AbteilungItem.DetailsClass, global::LightSwitchApplication.MitarbeiterItem>.Data _Abteilungsleiter;
            
        }
    
        #endregion
    }
    
    #endregion
}
