//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class SearchAbteilungItemSet
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SearchAbteilungItemSet() : base("LightSwitchApplication.InstControl.Desktopclient:SearchAbteilungItemSet")
        {
            global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SearchAbteilungItemSet CreateInstance()
        {
            return new global::LightSwitchApplication.SearchAbteilungItemSet(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchAbteilungItemSet_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchAbteilungItemSet_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchAbteilungItemSet_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchAbteilungItemSet_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchAbteilungItemSet_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchAbteilungItemSet_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchAbteilungItemSet_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void AbteilungItemSet_SelectionChanged();

        partial void AbteilungItemSet_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Loaded(bool succeeded);

        /// <summary>
        /// Ruft die visuelle AbteilungItemSet-Auflistung ab. Diese Auflistung enthält alle Datensätze, die derzeit in der entsprechenden Liste oder im entsprechenden Rastersteuerelement angezeigt werden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.AbteilungItem> AbteilungItemSet
        {
            get
            {
                return global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.GetValue(this, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySetProperties.AbteilungItemSet);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.CommandSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySetProperties.AbteilungItemSet;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass>.Entry
                __SearchAbteilungItemSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass>.Entry(
                    global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.__SearchAbteilungItemSet_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.__SearchAbteilungItemSet_InvokeSavingEvent,
                    global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.__SearchAbteilungItemSet_InvokeSavedEvent,
                    global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.__SearchAbteilungItemSet_InvokeClosingEvent,
                    global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.__SearchAbteilungItemSet_InvokeCreated,
                    global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.__SearchAbteilungItemSet_InvokeActivated,
                    global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.__SearchAbteilungItemSet_InvokeSaveErrorEvent);
            private static void __SearchAbteilungItemSet_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SearchAbteilungItemSet s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SearchAbteilungItemSet_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SearchAbteilungItemSet_InvokeSavingEvent(global::LightSwitchApplication.SearchAbteilungItemSet s)
            {
                bool handled = false;
                s.SearchAbteilungItemSet_Saving(ref handled);
                return handled;
            }
            private static void __SearchAbteilungItemSet_InvokeSavedEvent(global::LightSwitchApplication.SearchAbteilungItemSet s)
            {
                s.SearchAbteilungItemSet_Saved();
            }
            private static bool __SearchAbteilungItemSet_InvokeClosingEvent(global::LightSwitchApplication.SearchAbteilungItemSet s)
            {
                bool cancel = false;
                s.SearchAbteilungItemSet_Closing(ref cancel);
                return cancel;
            }
            private static void __SearchAbteilungItemSet_InvokeCreated(global::LightSwitchApplication.SearchAbteilungItemSet s)
            {
                s.SearchAbteilungItemSet_Created();
            }
            private static void __SearchAbteilungItemSet_InvokeActivated(global::LightSwitchApplication.SearchAbteilungItemSet s)
            {
                s.SearchAbteilungItemSet_Activated();
            }
            private static bool __SearchAbteilungItemSet_InvokeSaveErrorEvent(global::LightSwitchApplication.SearchAbteilungItemSet s, global::System.Exception ex)
            {
                bool handled = false;
                s.SearchAbteilungItemSet_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable AbteilungItemSetQuery()
            {
                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    this.Screen.DataWorkspace.ApplicationData.AbteilungItemSet,
                    "Abteilungsleiter");
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass, global::LightSwitchApplication.AbteilungItem>.Data _AbteilungItemSet;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass, global::LightSwitchApplication.AbteilungItem> AbteilungItemSet
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass, global::LightSwitchApplication.AbteilungItem>)base.GetItem(global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySetProperties.AbteilungItemSet);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass, global::LightSwitchApplication.AbteilungItem>.Entry
                    AbteilungItemSet = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass, global::LightSwitchApplication.AbteilungItem>.Entry(
                        "AbteilungItemSet",
                        global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySetProperties._AbteilungItemSet_Stub,
                        global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySetProperties._AbteilungItemSet_Validate,
                        global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySetProperties._AbteilungItemSet_CreateQuery,
                        global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySetProperties._AbteilungItemSet_SelectionChanged,
                        global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySetProperties._AbteilungItemSet_OnCollectionChanged,
                        global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass.PropertySetProperties._AbteilungItemSet_OnLoaded);
                private static void _AbteilungItemSet_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchAbteilungItemSet, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass, global::LightSwitchApplication.AbteilungItem>.Data> c, global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass d, object sf)
                {
                    c(d, ref d._AbteilungItemSet, sf);
                }
                private static void _AbteilungItemSet_Validate(global::LightSwitchApplication.SearchAbteilungItemSet s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.AbteilungItemSet_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _AbteilungItemSet_CreateQuery(global::LightSwitchApplication.SearchAbteilungItemSet.DetailsClass d, object[] args)
                {
                    return d.AbteilungItemSetQuery();
                }
                private static void _AbteilungItemSet_SelectionChanged(global::LightSwitchApplication.SearchAbteilungItemSet s)
                {
                    s.AbteilungItemSet_SelectionChanged();
                }
                private static void _AbteilungItemSet_OnCollectionChanged(global::LightSwitchApplication.SearchAbteilungItemSet s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.AbteilungItemSet_Changed(e);
                }
                private static void _AbteilungItemSet_OnLoaded(global::LightSwitchApplication.SearchAbteilungItemSet s, bool succeeded)
                {
                    s.AbteilungItemSet_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
