//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Inserting(global::LightSwitchApplication.AbteilungItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Inserted(global::LightSwitchApplication.AbteilungItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Updating(global::LightSwitchApplication.AbteilungItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Updated(global::LightSwitchApplication.AbteilungItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Deleting(global::LightSwitchApplication.AbteilungItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Deleted(global::LightSwitchApplication.AbteilungItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Validate(global::LightSwitchApplication.AbteilungItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AbteilungItemSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.AbteilungItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_Inserting(global::LightSwitchApplication.BeschäftigungsArtItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_Inserted(global::LightSwitchApplication.BeschäftigungsArtItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_Updating(global::LightSwitchApplication.BeschäftigungsArtItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_Updated(global::LightSwitchApplication.BeschäftigungsArtItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_Deleting(global::LightSwitchApplication.BeschäftigungsArtItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_Deleted(global::LightSwitchApplication.BeschäftigungsArtItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_Validate(global::LightSwitchApplication.BeschäftigungsArtItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BeschäftigungsArtItemSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.BeschäftigungsArtItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_Inserting(global::LightSwitchApplication.MitarbeiterItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_Inserted(global::LightSwitchApplication.MitarbeiterItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_Updating(global::LightSwitchApplication.MitarbeiterItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_Updated(global::LightSwitchApplication.MitarbeiterItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_Deleting(global::LightSwitchApplication.MitarbeiterItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_Deleted(global::LightSwitchApplication.MitarbeiterItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_Validate(global::LightSwitchApplication.MitarbeiterItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterItemSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MitarbeiterItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_Inserting(global::LightSwitchApplication.ProjektItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_Inserted(global::LightSwitchApplication.ProjektItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_Updating(global::LightSwitchApplication.ProjektItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_Updated(global::LightSwitchApplication.ProjektItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_Deleting(global::LightSwitchApplication.ProjektItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_Deleted(global::LightSwitchApplication.ProjektItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_Validate(global::LightSwitchApplication.ProjektItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ProjektItemSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.ProjektItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_Inserting(global::LightSwitchApplication.StellenanteilItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_Inserted(global::LightSwitchApplication.StellenanteilItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_Updating(global::LightSwitchApplication.StellenanteilItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_Updated(global::LightSwitchApplication.StellenanteilItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_Deleting(global::LightSwitchApplication.StellenanteilItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_Deleted(global::LightSwitchApplication.StellenanteilItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_Validate(global::LightSwitchApplication.StellenanteilItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StellenanteilItemSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StellenanteilItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_Inserting(global::LightSwitchApplication.VertragItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_Inserted(global::LightSwitchApplication.VertragItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_Updating(global::LightSwitchApplication.VertragItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_Updated(global::LightSwitchApplication.VertragItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_Deleting(global::LightSwitchApplication.VertragItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_Deleted(global::LightSwitchApplication.VertragItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_Validate(global::LightSwitchApplication.VertragItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragItemSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.VertragItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_Inserting(global::LightSwitchApplication.VertragJeMonatItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_Inserted(global::LightSwitchApplication.VertragJeMonatItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_Updating(global::LightSwitchApplication.VertragJeMonatItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_Updated(global::LightSwitchApplication.VertragJeMonatItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_Deleting(global::LightSwitchApplication.VertragJeMonatItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_Deleted(global::LightSwitchApplication.VertragJeMonatItem entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_Validate(global::LightSwitchApplication.VertragJeMonatItem entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void VertragJeMonatItemSet_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.VertragJeMonatItem, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterAusgeschieden_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterAusgeschieden_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterAusgeschieden_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterAusgeschieden_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MitarbeiterItem> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterAusgeschieden_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterMitAktuellemVertrag_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterMitAktuellemVertrag_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterMitAktuellemVertrag_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterMitAktuellemVertrag_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MitarbeiterItem> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterMitAktuellemVertrag_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterMitAuslaufendemVertrag_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterMitAuslaufendemVertrag_Executing(global::System.Nullable<int> Monate);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterMitAuslaufendemVertrag_PreprocessQuery(global::System.Nullable<int> Monate, ref global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterMitAuslaufendemVertrag_Executed(global::System.Nullable<int> Monate, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MitarbeiterItem> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterMitAuslaufendemVertrag_ExecuteFailed(global::System.Nullable<int> Monate, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterOhneAktuellenVertrag_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterOhneAktuellenVertrag_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MitarbeiterOhneAktuellenVertrag_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterOhneAktuellenVertrag_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MitarbeiterItem> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        partial void MitarbeiterOhneAktuellenVertrag_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ApplicationData_InitializingConnection(global::Microsoft.LightSwitch.DatabaseConnectionState state);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.AbteilungItem>
                __AbteilungItemSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.AbteilungItem>(
                    "AbteilungItemSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__AbteilungItemSet_Filter);
            private static bool __AbteilungItemSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.AbteilungItemSet_CanInsert(ref result);
                return result;
            }
            private static bool __AbteilungItemSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.AbteilungItemSet_CanUpdate(ref result);
                return result;
            }
            private static bool __AbteilungItemSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.AbteilungItemSet_CanDelete(ref result);
                return result;
            }
            private static bool __AbteilungItemSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.AbteilungItemSet_CanRead(ref result);
                return result;
            }
            private static void __AbteilungItemSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.AbteilungItem e)
            {
                d.AbteilungItemSet_Inserting(e);
            }
            private static void __AbteilungItemSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.AbteilungItem e)
            {
                d.AbteilungItemSet_Inserted(e);
            }
            private static void __AbteilungItemSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.AbteilungItem e)
            {
                d.AbteilungItemSet_Updating(e);
            }
            private static void __AbteilungItemSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.AbteilungItem e)
            {
                d.AbteilungItemSet_Updated(e);
            }
            private static void __AbteilungItemSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.AbteilungItem e)
            {
                d.AbteilungItemSet_Deleting(e);
            }
            private static void __AbteilungItemSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.AbteilungItem e)
            {
                d.AbteilungItemSet_Deleted(e);
            }
            private static void __AbteilungItemSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.AbteilungItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.AbteilungItemSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.AbteilungItem, bool>> __AbteilungItemSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.AbteilungItem, bool>> filter = null;
                d.AbteilungItemSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.BeschäftigungsArtItem>
                __BeschäftigungsArtItemSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.BeschäftigungsArtItem>(
                    "BeschäftigungsArtItemSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__BeschäftigungsArtItemSet_Filter);
            private static bool __BeschäftigungsArtItemSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.BeschäftigungsArtItemSet_CanInsert(ref result);
                return result;
            }
            private static bool __BeschäftigungsArtItemSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.BeschäftigungsArtItemSet_CanUpdate(ref result);
                return result;
            }
            private static bool __BeschäftigungsArtItemSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.BeschäftigungsArtItemSet_CanDelete(ref result);
                return result;
            }
            private static bool __BeschäftigungsArtItemSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.BeschäftigungsArtItemSet_CanRead(ref result);
                return result;
            }
            private static void __BeschäftigungsArtItemSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.BeschäftigungsArtItem e)
            {
                d.BeschäftigungsArtItemSet_Inserting(e);
            }
            private static void __BeschäftigungsArtItemSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.BeschäftigungsArtItem e)
            {
                d.BeschäftigungsArtItemSet_Inserted(e);
            }
            private static void __BeschäftigungsArtItemSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.BeschäftigungsArtItem e)
            {
                d.BeschäftigungsArtItemSet_Updating(e);
            }
            private static void __BeschäftigungsArtItemSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.BeschäftigungsArtItem e)
            {
                d.BeschäftigungsArtItemSet_Updated(e);
            }
            private static void __BeschäftigungsArtItemSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.BeschäftigungsArtItem e)
            {
                d.BeschäftigungsArtItemSet_Deleting(e);
            }
            private static void __BeschäftigungsArtItemSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.BeschäftigungsArtItem e)
            {
                d.BeschäftigungsArtItemSet_Deleted(e);
            }
            private static void __BeschäftigungsArtItemSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.BeschäftigungsArtItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.BeschäftigungsArtItemSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.BeschäftigungsArtItem, bool>> __BeschäftigungsArtItemSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.BeschäftigungsArtItem, bool>> filter = null;
                d.BeschäftigungsArtItemSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>
                __MitarbeiterItemSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>(
                    "MitarbeiterItemSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterItemSet_Filter);
            private static bool __MitarbeiterItemSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MitarbeiterItemSet_CanInsert(ref result);
                return result;
            }
            private static bool __MitarbeiterItemSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MitarbeiterItemSet_CanUpdate(ref result);
                return result;
            }
            private static bool __MitarbeiterItemSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MitarbeiterItemSet_CanDelete(ref result);
                return result;
            }
            private static bool __MitarbeiterItemSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.MitarbeiterItemSet_CanRead(ref result);
                return result;
            }
            private static void __MitarbeiterItemSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MitarbeiterItem e)
            {
                d.MitarbeiterItemSet_Inserting(e);
            }
            private static void __MitarbeiterItemSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MitarbeiterItem e)
            {
                d.MitarbeiterItemSet_Inserted(e);
            }
            private static void __MitarbeiterItemSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MitarbeiterItem e)
            {
                d.MitarbeiterItemSet_Updating(e);
            }
            private static void __MitarbeiterItemSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MitarbeiterItem e)
            {
                d.MitarbeiterItemSet_Updated(e);
            }
            private static void __MitarbeiterItemSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MitarbeiterItem e)
            {
                d.MitarbeiterItemSet_Deleting(e);
            }
            private static void __MitarbeiterItemSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MitarbeiterItem e)
            {
                d.MitarbeiterItemSet_Deleted(e);
            }
            private static void __MitarbeiterItemSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.MitarbeiterItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.MitarbeiterItemSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MitarbeiterItem, bool>> __MitarbeiterItemSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.MitarbeiterItem, bool>> filter = null;
                d.MitarbeiterItemSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.ProjektItem>
                __ProjektItemSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.ProjektItem>(
                    "ProjektItemSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ProjektItemSet_Filter);
            private static bool __ProjektItemSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ProjektItemSet_CanInsert(ref result);
                return result;
            }
            private static bool __ProjektItemSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ProjektItemSet_CanUpdate(ref result);
                return result;
            }
            private static bool __ProjektItemSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ProjektItemSet_CanDelete(ref result);
                return result;
            }
            private static bool __ProjektItemSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.ProjektItemSet_CanRead(ref result);
                return result;
            }
            private static void __ProjektItemSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ProjektItem e)
            {
                d.ProjektItemSet_Inserting(e);
            }
            private static void __ProjektItemSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ProjektItem e)
            {
                d.ProjektItemSet_Inserted(e);
            }
            private static void __ProjektItemSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ProjektItem e)
            {
                d.ProjektItemSet_Updating(e);
            }
            private static void __ProjektItemSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ProjektItem e)
            {
                d.ProjektItemSet_Updated(e);
            }
            private static void __ProjektItemSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ProjektItem e)
            {
                d.ProjektItemSet_Deleting(e);
            }
            private static void __ProjektItemSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ProjektItem e)
            {
                d.ProjektItemSet_Deleted(e);
            }
            private static void __ProjektItemSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.ProjektItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.ProjektItemSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.ProjektItem, bool>> __ProjektItemSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.ProjektItem, bool>> filter = null;
                d.ProjektItemSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.StellenanteilItem>
                __StellenanteilItemSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.StellenanteilItem>(
                    "StellenanteilItemSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__StellenanteilItemSet_Filter);
            private static bool __StellenanteilItemSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StellenanteilItemSet_CanInsert(ref result);
                return result;
            }
            private static bool __StellenanteilItemSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StellenanteilItemSet_CanUpdate(ref result);
                return result;
            }
            private static bool __StellenanteilItemSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StellenanteilItemSet_CanDelete(ref result);
                return result;
            }
            private static bool __StellenanteilItemSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.StellenanteilItemSet_CanRead(ref result);
                return result;
            }
            private static void __StellenanteilItemSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StellenanteilItem e)
            {
                d.StellenanteilItemSet_Inserting(e);
            }
            private static void __StellenanteilItemSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StellenanteilItem e)
            {
                d.StellenanteilItemSet_Inserted(e);
            }
            private static void __StellenanteilItemSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StellenanteilItem e)
            {
                d.StellenanteilItemSet_Updating(e);
            }
            private static void __StellenanteilItemSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StellenanteilItem e)
            {
                d.StellenanteilItemSet_Updated(e);
            }
            private static void __StellenanteilItemSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StellenanteilItem e)
            {
                d.StellenanteilItemSet_Deleting(e);
            }
            private static void __StellenanteilItemSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StellenanteilItem e)
            {
                d.StellenanteilItemSet_Deleted(e);
            }
            private static void __StellenanteilItemSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.StellenanteilItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.StellenanteilItemSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StellenanteilItem, bool>> __StellenanteilItemSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.StellenanteilItem, bool>> filter = null;
                d.StellenanteilItemSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.VertragItem>
                __VertragItemSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.VertragItem>(
                    "VertragItemSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragItemSet_Filter);
            private static bool __VertragItemSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.VertragItemSet_CanInsert(ref result);
                return result;
            }
            private static bool __VertragItemSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.VertragItemSet_CanUpdate(ref result);
                return result;
            }
            private static bool __VertragItemSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.VertragItemSet_CanDelete(ref result);
                return result;
            }
            private static bool __VertragItemSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.VertragItemSet_CanRead(ref result);
                return result;
            }
            private static void __VertragItemSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragItem e)
            {
                d.VertragItemSet_Inserting(e);
            }
            private static void __VertragItemSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragItem e)
            {
                d.VertragItemSet_Inserted(e);
            }
            private static void __VertragItemSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragItem e)
            {
                d.VertragItemSet_Updating(e);
            }
            private static void __VertragItemSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragItem e)
            {
                d.VertragItemSet_Updated(e);
            }
            private static void __VertragItemSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragItem e)
            {
                d.VertragItemSet_Deleting(e);
            }
            private static void __VertragItemSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragItem e)
            {
                d.VertragItemSet_Deleted(e);
            }
            private static void __VertragItemSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.VertragItemSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.VertragItem, bool>> __VertragItemSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.VertragItem, bool>> filter = null;
                d.VertragItemSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.VertragJeMonatItem>
                __VertragJeMonatItemSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.VertragJeMonatItem>(
                    "VertragJeMonatItemSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_Validate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__VertragJeMonatItemSet_Filter);
            private static bool __VertragJeMonatItemSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.VertragJeMonatItemSet_CanInsert(ref result);
                return result;
            }
            private static bool __VertragJeMonatItemSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.VertragJeMonatItemSet_CanUpdate(ref result);
                return result;
            }
            private static bool __VertragJeMonatItemSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.VertragJeMonatItemSet_CanDelete(ref result);
                return result;
            }
            private static bool __VertragJeMonatItemSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.VertragJeMonatItemSet_CanRead(ref result);
                return result;
            }
            private static void __VertragJeMonatItemSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragJeMonatItem e)
            {
                d.VertragJeMonatItemSet_Inserting(e);
            }
            private static void __VertragJeMonatItemSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragJeMonatItem e)
            {
                d.VertragJeMonatItemSet_Inserted(e);
            }
            private static void __VertragJeMonatItemSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragJeMonatItem e)
            {
                d.VertragJeMonatItemSet_Updating(e);
            }
            private static void __VertragJeMonatItemSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragJeMonatItem e)
            {
                d.VertragJeMonatItemSet_Updated(e);
            }
            private static void __VertragJeMonatItemSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragJeMonatItem e)
            {
                d.VertragJeMonatItemSet_Deleting(e);
            }
            private static void __VertragJeMonatItemSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragJeMonatItem e)
            {
                d.VertragJeMonatItemSet_Deleted(e);
            }
            private static void __VertragJeMonatItemSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.VertragJeMonatItem e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.VertragJeMonatItemSet_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.VertragJeMonatItem, bool>> __VertragJeMonatItemSet_Filter(global::LightSwitchApplication.ApplicationDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.VertragJeMonatItem, bool>> filter = null;
                d.VertragJeMonatItemSet_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>
                __MitarbeiterAusgeschiedenEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>(
                    "MitarbeiterAusgeschieden",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterAusgeschieden_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterAusgeschieden_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterAusgeschieden_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterAusgeschieden_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterAusgeschieden_PreprocessQuery);
            private static bool __MitarbeiterAusgeschieden_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.MitarbeiterAusgeschieden_CanExecute(ref r);
                return r;
            }
            private static void __MitarbeiterAusgeschieden_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MitarbeiterAusgeschieden_Executing();
            }
            private static void __MitarbeiterAusgeschieden_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MitarbeiterAusgeschieden_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MitarbeiterItem>)args[0]);
            }
            private static void __MitarbeiterAusgeschieden_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.MitarbeiterAusgeschieden_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __MitarbeiterAusgeschieden_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem>)args[0];
                d.MitarbeiterAusgeschieden_PreprocessQuery(ref query);
                return query;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>
                __MitarbeiterMitAktuellemVertragEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>(
                    "MitarbeiterMitAktuellemVertrag",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAktuellemVertrag_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAktuellemVertrag_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAktuellemVertrag_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAktuellemVertrag_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAktuellemVertrag_PreprocessQuery);
            private static bool __MitarbeiterMitAktuellemVertrag_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.MitarbeiterMitAktuellemVertrag_CanExecute(ref r);
                return r;
            }
            private static void __MitarbeiterMitAktuellemVertrag_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MitarbeiterMitAktuellemVertrag_Executing();
            }
            private static void __MitarbeiterMitAktuellemVertrag_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MitarbeiterMitAktuellemVertrag_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MitarbeiterItem>)args[0]);
            }
            private static void __MitarbeiterMitAktuellemVertrag_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.MitarbeiterMitAktuellemVertrag_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __MitarbeiterMitAktuellemVertrag_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem>)args[0];
                d.MitarbeiterMitAktuellemVertrag_PreprocessQuery(ref query);
                return query;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>
                __MitarbeiterMitAuslaufendemVertragEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>(
                    "MitarbeiterMitAuslaufendemVertrag",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAuslaufendemVertrag_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAuslaufendemVertrag_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAuslaufendemVertrag_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAuslaufendemVertrag_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterMitAuslaufendemVertrag_PreprocessQuery);
            private static bool __MitarbeiterMitAuslaufendemVertrag_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.MitarbeiterMitAuslaufendemVertrag_CanExecute(ref r);
                return r;
            }
            private static void __MitarbeiterMitAuslaufendemVertrag_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MitarbeiterMitAuslaufendemVertrag_Executing((global::System.Nullable<int>)args[0]);
            }
            private static void __MitarbeiterMitAuslaufendemVertrag_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MitarbeiterMitAuslaufendemVertrag_Executed((global::System.Nullable<int>)args[0], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MitarbeiterItem>)args[1]);
            }
            private static void __MitarbeiterMitAuslaufendemVertrag_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.MitarbeiterMitAuslaufendemVertrag_ExecuteFailed((global::System.Nullable<int>)args[0], ex);
            }
            private static global::System.Linq.IQueryable __MitarbeiterMitAuslaufendemVertrag_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem>)args[1];
                d.MitarbeiterMitAuslaufendemVertrag_PreprocessQuery((global::System.Nullable<int>)args[0], ref query);
                return query;
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>
                __MitarbeiterOhneAktuellenVertragEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.MitarbeiterItem>(
                    "MitarbeiterOhneAktuellenVertrag",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterOhneAktuellenVertrag_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterOhneAktuellenVertrag_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterOhneAktuellenVertrag_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterOhneAktuellenVertrag_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__MitarbeiterOhneAktuellenVertrag_PreprocessQuery);
            private static bool __MitarbeiterOhneAktuellenVertrag_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.MitarbeiterOhneAktuellenVertrag_CanExecute(ref r);
                return r;
            }
            private static void __MitarbeiterOhneAktuellenVertrag_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MitarbeiterOhneAktuellenVertrag_Executing();
            }
            private static void __MitarbeiterOhneAktuellenVertrag_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.MitarbeiterOhneAktuellenVertrag_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.MitarbeiterItem>)args[0]);
            }
            private static void __MitarbeiterOhneAktuellenVertrag_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.MitarbeiterOhneAktuellenVertrag_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __MitarbeiterOhneAktuellenVertrag_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.MitarbeiterItem>)args[0];
                d.MitarbeiterOhneAktuellenVertrag_PreprocessQuery(ref query);
                return query;
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>
                ___DatabaseAuthEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.DatabaseAuthEntry<global::LightSwitchApplication.ApplicationDataService>(
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__ApplicationData_InitializingConnection);
            private static void __ApplicationData_InitializingConnection(global::LightSwitchApplication.ApplicationDataService d, global::Microsoft.LightSwitch.DatabaseConnectionState state)
            {
                d.ApplicationData_InitializingConnection(state);
            }
        }
    
        #endregion
    }
    
    /// <summary>
    /// Provides members to query and update data in the WCF_RIA_ServiceData datasource.
    /// </summary>
    public sealed partial class WCF_RIA_ServiceDataService
        : global::LightSwitchApplication.WCF_RIA_ServiceData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public WCF_RIA_ServiceDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EnhancedMitarbeiters_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EnhancedMitarbeiters_Validate(global::LightSwitchApplication.EnhancedMitarbeiter entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline")]
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.WCF_RIA_ServiceDataService, global::LightSwitchApplication.EnhancedMitarbeiter>
                __EnhancedMitarbeitersEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.WCF_RIA_ServiceDataService, global::LightSwitchApplication.EnhancedMitarbeiter>(
                    "EnhancedMitarbeiters",
                    null,
                    null,
                    null,
                    global::LightSwitchApplication.WCF_RIA_ServiceDataService.DetailsClass.__EnhancedMitarbeiters_CanRead,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    global::LightSwitchApplication.WCF_RIA_ServiceDataService.DetailsClass.__EnhancedMitarbeiters_Validate,
                    null);
            private static bool __EnhancedMitarbeiters_CanRead(global::LightSwitchApplication.WCF_RIA_ServiceDataService d)
            {
                bool result = true;
                d.EnhancedMitarbeiters_CanRead(ref result);
                return result;
            }
            private static void __EnhancedMitarbeiters_Validate(global::LightSwitchApplication.WCF_RIA_ServiceDataService d, global::LightSwitchApplication.EnhancedMitarbeiter e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.EnhancedMitarbeiters_Validate(e, r);
            }
            
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.WCF_RIA_ServiceDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.WCF_RIA_ServiceDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.WCF_RIA_ServiceDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.WCF_RIA_ServiceDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.WCF_RIA_ServiceDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.WCF_RIA_ServiceDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.WCF_RIA_ServiceDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.WCF_RIA_ServiceDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.WCF_RIA_ServiceDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.WCF_RIA_ServiceDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.WCF_RIA_ServiceDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.WCF_RIA_ServiceDataService>(
                    global::LightSwitchApplication.WCF_RIA_ServiceDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.WCF_RIA_ServiceDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.WCF_RIA_ServiceDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.WCF_RIA_ServiceDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.WCF_RIA_ServiceDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.WCF_RIA_ServiceDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
        }
    
        #endregion
    }
    
    #endregion
}
