

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class EnhancedMitarbeiter : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the EnhancedMitarbeiter entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EnhancedMitarbeiter()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public EnhancedMitarbeiter(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EnhancedMitarbeiter> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EnhancedMitarbeiter_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EnhancedMitarbeiter_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ID
        {
            get
            {
                return global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.GetValue(this, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.ID);
            }
            set
            {
                global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.SetValue(this, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.ID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UserID
        {
            get
            {
                return global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.GetValue(this, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.UserID);
            }
            set
            {
                global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.SetValue(this, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.UserID, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void UserID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime aktuellerVertragBis
        {
            get
            {
                return global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.GetValue(this, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.aktuellerVertragBis);
            }
            set
            {
                global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.SetValue(this, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.aktuellerVertragBis, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void aktuellerVertragBis_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void aktuellerVertragBis_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void aktuellerVertragBis_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.EnhancedMitarbeiter,
                global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass,
                global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.IImplementation,
                global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.ID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass>.Entry
                __EnhancedMitarbeiterEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass>.Entry(
                    global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.__EnhancedMitarbeiter_CreateNew,
                    global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.__EnhancedMitarbeiter_Created,
                    global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.__EnhancedMitarbeiter_AllowSaveWithErrors);
            private static global::LightSwitchApplication.EnhancedMitarbeiter __EnhancedMitarbeiter_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.EnhancedMitarbeiter> es)
            {
                return new global::LightSwitchApplication.EnhancedMitarbeiter(es);
            }
            private static void __EnhancedMitarbeiter_Created(global::LightSwitchApplication.EnhancedMitarbeiter e)
            {
                e.EnhancedMitarbeiter_Created();
            }
            private static bool __EnhancedMitarbeiter_AllowSaveWithErrors(global::LightSwitchApplication.EnhancedMitarbeiter e)
            {
                bool result = false;
                e.EnhancedMitarbeiter_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, int> ID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.ID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, string> UserID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.UserID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, global::System.DateTime> aktuellerVertragBis
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties.aktuellerVertragBis) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, global::System.DateTime>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ID { get; set; }
                new string UserID { get; set; }
                new global::System.DateTime aktuellerVertragBis { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, int>.Entry
                    ID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, int>.Entry(
                        "ID",
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._ID_Stub,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._ID_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._ID_Validate,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._ID_GetImplementationValue,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._ID_SetImplementationValue,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._ID_OnValueChanged);
                private static void _ID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, int>.Data> c, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass d, object sf)
                {
                    c(d, ref d._ID, sf);
                }
                private static bool _ID_ComputeIsReadOnly(global::LightSwitchApplication.EnhancedMitarbeiter e)
                {
                    bool result = false;
                    e.ID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ID_Validate(global::LightSwitchApplication.EnhancedMitarbeiter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ID_Validate(r);
                }
                private static int _ID_GetImplementationValue(global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass d)
                {
                    return d.ImplementationEntity.ID;
                }
                private static void _ID_SetImplementationValue(global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ID = v;
                }
                private static void _ID_OnValueChanged(global::LightSwitchApplication.EnhancedMitarbeiter e)
                {
                    e.ID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, string>.Entry
                    UserID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, string>.Entry(
                        "UserID",
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._UserID_Stub,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._UserID_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._UserID_Validate,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._UserID_GetImplementationValue,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._UserID_SetImplementationValue,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._UserID_OnValueChanged);
                private static void _UserID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, string>.Data> c, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass d, object sf)
                {
                    c(d, ref d._UserID, sf);
                }
                private static bool _UserID_ComputeIsReadOnly(global::LightSwitchApplication.EnhancedMitarbeiter e)
                {
                    bool result = false;
                    e.UserID_IsReadOnly(ref result);
                    return result;
                }
                private static void _UserID_Validate(global::LightSwitchApplication.EnhancedMitarbeiter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.UserID_Validate(r);
                }
                private static string _UserID_GetImplementationValue(global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass d)
                {
                    return d.ImplementationEntity.UserID;
                }
                private static void _UserID_SetImplementationValue(global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass d, string v)
                {
                    d.ImplementationEntity.UserID = v;
                }
                private static void _UserID_OnValueChanged(global::LightSwitchApplication.EnhancedMitarbeiter e)
                {
                    e.UserID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, global::System.DateTime>.Entry
                    aktuellerVertragBis = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, global::System.DateTime>.Entry(
                        "aktuellerVertragBis",
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._aktuellerVertragBis_Stub,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._aktuellerVertragBis_ComputeIsReadOnly,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._aktuellerVertragBis_Validate,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._aktuellerVertragBis_GetImplementationValue,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._aktuellerVertragBis_SetImplementationValue,
                        global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.PropertySetProperties._aktuellerVertragBis_OnValueChanged);
                private static void _aktuellerVertragBis_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass d, object sf)
                {
                    c(d, ref d._aktuellerVertragBis, sf);
                }
                private static bool _aktuellerVertragBis_ComputeIsReadOnly(global::LightSwitchApplication.EnhancedMitarbeiter e)
                {
                    bool result = false;
                    e.aktuellerVertragBis_IsReadOnly(ref result);
                    return result;
                }
                private static void _aktuellerVertragBis_Validate(global::LightSwitchApplication.EnhancedMitarbeiter e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.aktuellerVertragBis_Validate(r);
                }
                private static global::System.DateTime _aktuellerVertragBis_GetImplementationValue(global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass d)
                {
                    return d.ImplementationEntity.aktuellerVertragBis;
                }
                private static void _aktuellerVertragBis_SetImplementationValue(global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.aktuellerVertragBis = global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass.TruncateDate(v);
                }
                private static void _aktuellerVertragBis_OnValueChanged(global::LightSwitchApplication.EnhancedMitarbeiter e)
                {
                    e.aktuellerVertragBis_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, int>.Data _ID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, string>.Data _UserID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.EnhancedMitarbeiter, global::LightSwitchApplication.EnhancedMitarbeiter.DetailsClass, global::System.DateTime>.Data _aktuellerVertragBis;
            
        }
    
        #endregion
    }
    
    #endregion
}
