//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WCF_RIA_ServiceData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WCF_RIA_ServiceData object using the connection string found in the 'WCF_RIA_ServiceData' section of the application configuration file.
        /// </summary>
        public WCF_RIA_ServiceData() : base("name=WCF_RIA_ServiceData", "WCF_RIA_ServiceData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WCF_RIA_ServiceData object.
        /// </summary>
        public WCF_RIA_ServiceData(string connectionString) : base(connectionString, "WCF_RIA_ServiceData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WCF_RIA_ServiceData object.
        /// </summary>
        public WCF_RIA_ServiceData(EntityConnection connection) : base(connection, "WCF_RIA_ServiceData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EnhancedMitarbeiter> EnhancedMitarbeiters
        {
            get
            {
                if ((_EnhancedMitarbeiters == null))
                {
                    _EnhancedMitarbeiters = base.CreateObjectSet<EnhancedMitarbeiter>("EnhancedMitarbeiters");
                }
                return _EnhancedMitarbeiters;
            }
        }
        private ObjectSet<EnhancedMitarbeiter> _EnhancedMitarbeiters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EnhancedMitarbeiters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEnhancedMitarbeiters(EnhancedMitarbeiter enhancedMitarbeiter)
        {
            base.AddObject("EnhancedMitarbeiters", enhancedMitarbeiter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="EnhancedMitarbeiter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EnhancedMitarbeiter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EnhancedMitarbeiter object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="aktuellerVertragBis">Initial value of the aktuellerVertragBis property.</param>
        public static EnhancedMitarbeiter CreateEnhancedMitarbeiter(global::System.Int32 id, global::System.DateTime aktuellerVertragBis)
        {
            EnhancedMitarbeiter enhancedMitarbeiter = new EnhancedMitarbeiter();
            enhancedMitarbeiter.ID = id;
            enhancedMitarbeiter.aktuellerVertragBis = aktuellerVertragBis;
            return enhancedMitarbeiter;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = value;
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = value;
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime aktuellerVertragBis
        {
            get
            {
                return _aktuellerVertragBis;
            }
            set
            {
                OnaktuellerVertragBisChanging(value);
                ReportPropertyChanging("aktuellerVertragBis");
                _aktuellerVertragBis = value;
                ReportPropertyChanged("aktuellerVertragBis");
                OnaktuellerVertragBisChanged();
            }
        }
        private global::System.DateTime _aktuellerVertragBis;
        partial void OnaktuellerVertragBisChanging(global::System.DateTime value);
        partial void OnaktuellerVertragBisChanged();

        #endregion

    
    }

    #endregion

    
}
